# -*- coding: utf-8 -*-
"""HW-02_02_dl.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ftGcA5_Ap9lmX8DCO-3jFuJdT1NeLNGX
"""

import numpy as np
import torch
import torchvision.transforms as tvt
import os
from torch.utils.data import Dataset , DataLoader
import cv2
import random
from PIL import Image
import glob
import matplotlib.pyplot as plt
import time

!unzip Images.zip

images = glob.glob("Images/*.jpg")
for image in images:
  img = Image.open(image)
  plt.imshow(img)
  plt.show()

bottle_transform = tvt.Compose([tvt.RandomHorizontalFlip(),
                                tvt.Resize(500),
                                tvt.ColorJitter()
                                ])

class MyDataset(Dataset):
  def __init__(self, root):
    self.root = root
    self.img = ''
  
  def __len__(self):
    len = 0
    image = glob.glob(self.root + "/*.jpg")
    for image in images:
      len = len + 1
    
    return len
  
  def __getitem__(self, index):
    count = 0
    images = glob.glob(self.root+"/*.jpg")
    #tensor_image = torch.zeros(3,500,666).float()
    tensor_transform = tvt.Compose([
    tvt.ToTensor()
    ])
    for image in images:
      count = count + 1
      if(count == index):
        self.img = Image.open(image)    
  

    return (tensor_transform(bottle_transform(img)) , random.randint(0, 10))

my_dataset = MyDataset("Images")
print(len(my_dataset))
index = 10

print(my_dataset[index][0].shape , my_dataset[index][1])

index = 5
print(my_dataset[index][0].shape, my_dataset[index][1])

img = Image.open('Images/Bottle6.jpg')
img_trans = bottle_transform(img)
plt.subplot(1,2,1)
plt.imshow(img)
plt.subplot(1,2,2)
plt.imshow(img_trans)

img = Image.open('Images/Bottle1.jpg')
img_trans = bottle_transform(img)
plt.subplot(1,2,1)
plt.imshow(img)
plt.subplot(1,2,2)
plt.imshow(img_trans)

img = Image.open('Images/Bottle2.jpg')
img_trans = bottle_transform(img)
plt.subplot(1,2,1)
plt.imshow(img)
plt.subplot(1,2,2)
plt.imshow(img_trans)

"""Que 3:

"""

bottle = MyDataset("Images")
bottle_dataloader = DataLoader(bottle , batch_size = 4)



next_batch = next(iter(bottle_dataloader))
for i in range(0, 4):
  image = next_batch[0][i]
  transform = tvt.ToPILImage()
  image = transform(image)
  plt.imshow(image)
  plt.show()

import time
start = time.time()


data = []
k = 0
for i in range (0,1000):
  my_dataset = MyDataset("Images")
  my_dataset[k]
  k = k + 1
  if k == 10:
    k = 0
  

end = time.time()

start

end - start

import time
start = time.time()


data = []
for i in range (0,1000):
  my_dataset = MyDataset("Images")
  Data = DataLoader(my_dataset , batch_size = 2 , num_workers= 2)

end = time.time()



end - start

import time
start = time.time()


data = []
for i in range (0,1000):
  my_dataset = MyDataset("Images")
  Data = DataLoader(my_dataset , batch_size = 4 , num_workers= 3)

end = time.time()

end-start